// OTA manifest: a static JSON file the frame reads to decide whether to update.
//
//   {"env": "seeed-ee02", "version": "1.2.0",
//    "url": "https://.../inkfetch-seeed-ee02.bin", "sha256": "<64 hex chars>"}
//
// Generated by `inkfetch manifest` (tools/) and published with each release.
#pragma once

#include <cstddef>
#include <optional>
#include <string>

namespace inkfetch {

struct Version {
    unsigned major, minor, patch;
};

// "1.2.3" or "v1.2.3".
std::optional<Version> parseVersion(const std::string& text);
bool isNewer(const Version& candidate, const Version& current);

struct Manifest {
    std::string env;
    Version version;
    std::string url;
    std::string sha256;  // lowercase hex
};

enum class ManifestError { None, InvalidJson, MissingField, BadVersion, BadUrl, BadHash };

const char* describe(ManifestError error);

ManifestError parseManifest(const char* json, size_t length, Manifest& out);

// True when the manifest targets this build (`env`) and is newer than `current`.
bool shouldUpdate(const Manifest& manifest, const std::string& env, const Version& current);

}  // namespace inkfetch
